# Generated by Django 4.2 on 2023-06-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('info', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='default.jpg', upload_to='game_pics')),
                ('url', models.URLField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.type')),
            ],
        ),
    ]
